spring:

  ##GATEWAY CONFIGURATIONS
  cloud:
    gateway:
      routes:
        - id: naukri-api
          uri: http://localhost:8800
          predicates:
            - Path=/api-employee/**
          filters:
            - StripPrefix=1
        - id: naukri-api
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka